<?php

namespace Database\Seeders;

use App\Models\Wilayah;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WilayahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Wilayah::create(['id'  => '1', 'nama'  => 'Kabupaten Kampar', 'level' => '3', 'induk' => NULL]);
        Wilayah::create(['id'  => '2', 'nama'  => 'KECAMATAN BANGKINANG KOTA', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '3', 'nama'  => 'Kelurahan Bangkinang ', 'level' => '5', 'induk' => 2]);
        Wilayah::create(['id'  => '4', 'nama'  => 'desa riden permai', 'level' => '5', 'induk' => 2]);
        Wilayah::create(['id'  => '5', 'nama'  => 'Kelurahan Langgini', 'level' => '5', 'induk' => 2]);
        Wilayah::create(['id'  => '6', 'nama'  => 'Desa Kumantan', 'level' => '5', 'induk' => 2]);
        Wilayah::create(['id'  => '7', 'nama'  => 'KECAMATAN KUOK', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '8', 'nama'  => 'kuok ', 'level' => '5', 'induk' => 7]);
        Wilayah::create(['id'  => '9', 'nama'  => 'marangin', 'level' => '5', 'induk' => 7]);
        Wilayah::create(['id'  => '10', 'nama'  => 'empat balain', 'level' => '5', 'induk' => 7]);
        Wilayah::create(['id'  => '11', 'nama'  => 'pulau jambu', 'level' => '5', 'induk' => 7]);
        Wilayah::create(['id'  => '12', 'nama'  => 'silam', 'level' => '5', 'induk' => 7]);
        Wilayah::create(['id'  => '13', 'nama'  => 'bukit melintang', 'level' => '5', 'induk' => 7]);
        Wilayah::create(['id'  => '14', 'nama'  => 'lereng', 'level' => '5', 'induk' => 7]);
        Wilayah::create(['id'  => '15', 'nama'  => 'pulau terap', 'level' => '5', 'induk' => 7]);
        Wilayah::create(['id'  => '16', 'nama'  => 'batu langka kecil', 'level' => '5', 'induk' => 7]);
        Wilayah::create(['id'  => '17', 'nama'  => 'KECAMATAN BANGKINANG ', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '18', 'nama'  => 'pulau', 'level' => '5', 'induk' => 17]);
        Wilayah::create(['id'  => '19', 'nama'  => 'pasir sialang', 'level' => '5', 'induk' => 17]);
        Wilayah::create(['id'  => '20', 'nama'  => 'pulau lawas muara uwai', 'level' => '5', 'induk' => 17]);
        Wilayah::create(['id'  => '21', 'nama'  => 'bukit payung', 'level' => '5', 'induk' => 17]);
        Wilayah::create(['id'  => '22', 'nama'  => 'binuang', 'level' => '5', 'induk' => 17]);
        Wilayah::create(['id'  => '23', 'nama'  => 'bukit sembilan', 'level' => '5', 'induk' => 17]);
        Wilayah::create(['id'  => '24', 'nama'  => 'laboy jaya', 'level' => '5', 'induk' => 17]);
        Wilayah::create(['id'  => '25', 'nama'  => 'suka mulya', 'level' => '5', 'induk' => 17]);
        Wilayah::create(['id'  => '26', 'nama'  => 'KECAMATAN KAMPAR', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '27', 'nama'  => 'batu belah', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '28', 'nama'  => 'tanjung berulak', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '29', 'nama'  => 'penyasawan', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '30', 'nama'  => 'rumbio', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '31', 'nama'  => 'padang mutung', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '32', 'nama'  => 'pulau jambu', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '33', 'nama'  => 'simpang kubu', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '34', 'nama'  => 'naumbai', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '35', 'nama'  => 'limau manis', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '36', 'nama'  => 'ranah singkuang', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '37', 'nama'  => 'pulau tinggi', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '38', 'nama'  => 'bukit ranah', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '39', 'nama'  => 'ranah baru ', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '40', 'nama'  => 'pulau sarak ', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '41', 'nama'  => 'koto tibun', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '42', 'nama'  => 'ranah ', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '43', 'nama'  => 'tanjung rambutan', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '44', 'nama'  => 'air tiris', 'level' => '5', 'induk' => 26]);
        Wilayah::create(['id'  => '45', 'nama'  => 'KECAMATAN SALO', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '46', 'nama'  => 'ganting ', 'level' => '5', 'induk' => 45]);
        Wilayah::create(['id'  => '47', 'nama'  => 'sipungguk', 'level' => '5', 'induk' => 45]);
        Wilayah::create(['id'  => '48', 'nama'  => 'salo', 'level' => '5', 'induk' => 45]);
        Wilayah::create(['id'  => '49', 'nama'  => 'salo timur', 'level' => '5', 'induk' => 45]);
        Wilayah::create(['id'  => '50', 'nama'  => 'siabu', 'level' => '5', 'induk' => 45]);
        Wilayah::create(['id'  => '51', 'nama'  => 'ganting damai', 'level' => '5', 'induk' => 45]);
        Wilayah::create(['id'  => '52', 'nama'  => 'KECAMATAN KAMPAR TIMUR', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '53', 'nama'  => 'pulau rumbai', 'level' => '5', 'induk' => 52]);
        Wilayah::create(['id'  => '54', 'nama'  => 'kampar ', 'level' => '5', 'induk' => 52]);
        Wilayah::create(['id'  => '55', 'nama'  => 'koto perambahan', 'level' => '5', 'induk' => 52]);
        Wilayah::create(['id'  => '56', 'nama'  => 'pulau birandang ', 'level' => '5', 'induk' => 52]);
        Wilayah::create(['id'  => '57', 'nama'  => 'sungai putih', 'level' => '5', 'induk' => 52]);
        Wilayah::create(['id'  => '58', 'nama'  => 'deli makmur', 'level' => '5', 'induk' => 52]);
        Wilayah::create(['id'  => '59', 'nama'  => 'sungai turap ', 'level' => '5', 'induk' => 52]);
        Wilayah::create(['id'  => '60', 'nama'  => 'tanjung bungo', 'level' => '5', 'induk' => 52]);
        Wilayah::create(['id'  => '61', 'nama'  => 'sawah baru', 'level' => '5', 'induk' => 52]);
        Wilayah::create(['id'  => '62', 'nama'  => 'KECAMATAN KAMPAR UTARA', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '63', 'nama'  => 'kampung panjang ', 'level' => '5', 'induk' => 62]);
        Wilayah::create(['id'  => '64', 'nama'  => 'muara jalai', 'level' => '5', 'induk' => 62]);
        Wilayah::create(['id'  => '65', 'nama'  => 'sungai tonang', 'level' => '5', 'induk' => 62]);
        Wilayah::create(['id'  => '66', 'nama'  => 'sungai jalau ', 'level' => '5', 'induk' => 62]);
        Wilayah::create(['id'  => '67', 'nama'  => 'sawah', 'level' => '5', 'induk' => 62]);
        Wilayah::create(['id'  => '68', 'nama'  => 'kayu aro', 'level' => '5', 'induk' => 62]);
        Wilayah::create(['id'  => '69', 'nama'  => 'sendayan', 'level' => '5', 'induk' => 62]);
        Wilayah::create(['id'  => '70', 'nama'  => 'naga beralih', 'level' => '5', 'induk' => 62]);
        Wilayah::create(['id'  => '71', 'nama'  => 'KECAMATAN RUMBIO JAYA', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '72', 'nama'  => 'alam panjang ', 'level' => '5', 'induk' => 71]);
        Wilayah::create(['id'  => '73', 'nama'  => 'pulau payung', 'level' => '5', 'induk' => 71]);
        Wilayah::create(['id'  => '74', 'nama'  => 'teratak', 'level' => '5', 'induk' => 71]);
        Wilayah::create(['id'  => '75', 'nama'  => 'bukit keratai', 'level' => '5', 'induk' => 71]);
        Wilayah::create(['id'  => '76', 'nama'  => 'batang batindih', 'level' => '5', 'induk' => 71]);
        Wilayah::create(['id'  => '77', 'nama'  => 'tambusai', 'level' => '5', 'induk' => 71]);
        Wilayah::create(['id'  => '78', 'nama'  => 'simpang petai', 'level' => '5', 'induk' => 71]);
        Wilayah::create(['id'  => '79', 'nama'  => 'KECAMATAN TAMBANG', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '80', 'nama'  => 'kuapan', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '81', 'nama'  => 'aur sati', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '82', 'nama'  => 'padang luas ', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '83', 'nama'  => 'goboh', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '84', 'nama'  => 'rimbau panjang', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '85', 'nama'  => 'kemang indah', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '86', 'nama'  => 'parit baru', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '87', 'nama'  => 'sungai pinang', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '88', 'nama'  => 'kualu ', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '89', 'nama'  => 'tarai bangun', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '90', 'nama'  => 'pulau raya', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '91', 'nama'  => 'pulau permai', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '92', 'nama'  => 'balam jaya', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '93', 'nama'  => 'terantang', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '94', 'nama'  => 'taluk kenidai', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '95', 'nama'  => 'kualu nenas', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '96', 'nama'  => 'tambang', 'level' => '5', 'induk' => 79]);
        Wilayah::create(['id'  => '97', 'nama'  => 'KECAMATAN TAPUNG', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '98', 'nama'  => 'pagaruyung', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '99', 'nama'  => 'pancuran gading', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '100', 'nama'  => 'mukti sari ', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '101', 'nama'  => 'indra puri', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '102', 'nama'  => 'sumber makur', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '103', 'nama'  => 'indra sakti', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '104', 'nama'  => 'kijang rejo', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '105', 'nama'  => 'petapahan', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '106', 'nama'  => 'si lambu makmur', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '107', 'nama'  => 'muara mahat baru', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '108', 'nama'  => 'kenantan', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '109', 'nama'  => 'sibuak', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '110', 'nama'  => 'pantai cermin', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '111', 'nama'  => 'sei putih', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '112', 'nama'  => 'air terbit', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '113', 'nama'  => 'sari galu', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '114', 'nama'  => 'tri anunggal', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '115', 'nama'  => 'gading sari', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '116', 'nama'  => 'tanjungs awit', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '117', 'nama'  => 'patapahan jaya', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '118', 'nama'  => 'pelambaian', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '119', 'nama'  => 'sungai agung', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '120', 'nama'  => 'karya indah', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '121', 'nama'  => 'bencah kelubi', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '122', 'nama'  => 'batu gajah', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '123', 'nama'  => 'KECAMATAN PERHENTIAN RAJA', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '124', 'nama'  => 'hangtuah ', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '125', 'nama'  => 'kampung pinang ', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '126', 'nama'  => 'lubuk sakat', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '127', 'nama'  => 'sialang kumbang', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '128', 'nama'  => 'pantai raja', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '129', 'nama'  => 'KECAMATAN SIAK HULU', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '130', 'nama'  => 'buluh nipis', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '131', 'nama'  => 'pangkalan baru', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '132', 'nama'  => 'bulu cina', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '133', 'nama'  => 'baru', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '134', 'nama'  => 'pandau jaya', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '135', 'nama'  => 'kapau jaya', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '136', 'nama'  => 'tanjung balam', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '137', 'nama'  => 'kumbang jaya', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '138', 'nama'  => 'lubuk siam', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '139', 'nama'  => 'teratak buluh', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '140', 'nama'  => 'tanah merah', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '141', 'nama'  => 'pangkalan serik', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '142', 'nama'  => 'KECAMATAN KAMPAR KIRI', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '143', 'nama'  => 'lipat kain', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '144', 'nama'  => 'domo', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '145', 'nama'  => 'muara selaya', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '146', 'nama'  => 'iv koto setingkai', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '147', 'nama'  => 'padang sawah', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '148', 'nama'  => 'kuntu', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '149', 'nama'  => 'teluk paman', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '150', 'nama'  => 'sungai geringging', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '151', 'nama'  => 'sungai paku', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '152', 'nama'  => 'sungai rambai', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '153', 'nama'  => 'sungai raja', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '154', 'nama'  => 'sungai sarik', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '155', 'nama'  => 'tanjung harapan', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '156', 'nama'  => 'lipat kain utara', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '157', 'nama'  => 'lupat kain selatan', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '158', 'nama'  => 'kuntu darussalam', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '159', 'nama'  => 'tanjung mas', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '160', 'nama'  => 'sungai liti', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '161', 'nama'  => 'teluk paman timur', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '162', 'nama'  => 'sungai harapan', 'level' => '5', 'induk' => 97]);
        Wilayah::create(['id'  => '163', 'nama'  => 'KECAMATAN KAMPAR KIRI TENGAH', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '164', 'nama'  => 'penghidupan', 'level' => '5', 'induk' => 163]);
        Wilayah::create(['id'  => '165', 'nama'  => 'simalinyang', 'level' => '5', 'induk' => 163]);
        Wilayah::create(['id'  => '166', 'nama'  => 'mayang pongkai', 'level' => '5', 'induk' => 163]);
        Wilayah::create(['id'  => '167', 'nama'  => 'lubuksakai', 'level' => '5', 'induk' => 163]);
        Wilayah::create(['id'  => '168', 'nama'  => 'bina baru', 'level' => '5', 'induk' => 163]);
        Wilayah::create(['id'  => '169', 'nama'  => 'hidup baru', 'level' => '5', 'induk' => 163]);
        Wilayah::create(['id'  => '170', 'nama'  => 'karya bhakti', 'level' => '5', 'induk' => 163]);
        Wilayah::create(['id'  => '171', 'nama'  => 'koto damai', 'level' => '5', 'induk' => 163]);
        Wilayah::create(['id'  => '172', 'nama'  => 'utama karya', 'level' => '5', 'induk' => 163]);
        Wilayah::create(['id'  => '173', 'nama'  => 'bukit sakai', 'level' => '5', 'induk' => 163]);
        Wilayah::create(['id'  => '174', 'nama'  => 'mekar jaya', 'level' => '5', 'induk' => 163]);
        Wilayah::create(['id'  => '175', 'nama'  => 'KECAMATAN KAMPAR KIRI HILIR', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '176', 'nama'  => 'sungai pagar ', 'level' => '5', 'induk' => 175]);
        Wilayah::create(['id'  => '177', 'nama'  => 'rantau kasih', 'level' => '5', 'induk' => 175]);
        Wilayah::create(['id'  => '178', 'nama'  => 'mentulik', 'level' => '5', 'induk' => 175]);
        Wilayah::create(['id'  => '179', 'nama'  => 'gading permai', 'level' => '5', 'induk' => 175]);
        Wilayah::create(['id'  => '180', 'nama'  => 'sungai bungo', 'level' => '5', 'induk' => 175]);
        Wilayah::create(['id'  => '181', 'nama'  => 'bangun sari ', 'level' => '5', 'induk' => 175]);
        Wilayah::create(['id'  => '182', 'nama'  => 'sungai petai', 'level' => '5', 'induk' => 175]);
        Wilayah::create(['id'  => '183', 'nama'  => 'sungai simpang dua', 'level' => '5', 'induk' => 175]);
        Wilayah::create(['id'  => '184', 'nama'  => 'KECAMATAN TAPUNG HILIR', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '185', 'nama'  => 'koto aman ', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '186', 'nama'  => 'kota baru', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '187', 'nama'  => 'suka maju', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '188', 'nama'  => 'kota bangun ', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '189', 'nama'  => 'tapung makmur', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '190', 'nama'  => 'cinta damai', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '191', 'nama'  => 'beringin lestari', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '192', 'nama'  => 'tandan sari', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '193', 'nama'  => 'tapung lestari', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '194', 'nama'  => 'tanah tinggi', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '195', 'nama'  => 'gerbang sari', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '196', 'nama'  => 'kijang jaya', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '197', 'nama'  => 'kijang makmur', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '198', 'nama'  => 'tebing lestari', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '199', 'nama'  => 'sekijang', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '200', 'nama'  => 'kota garo', 'level' => '5', 'induk' => 184]);
        Wilayah::create(['id'  => '201', 'nama'  => 'KECAMATAN TAPUNG HULU', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '202', 'nama'  => 'kasikan', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '203', 'nama'  => 'senama nenek ', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '204', 'nama'  => 'bukit kemuning', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '205', 'nama'  => 'suka ramai', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '206', 'nama'  => 'sumber sari', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '207', 'nama'  => 'tanah datar', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '208', 'nama'  => 'intan jaya', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '209', 'nama'  => 'rimba jaya', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '210', 'nama'  => 'rimba makmur', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '211', 'nama'  => 'muara intan', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '212', 'nama'  => 'rimba beringin', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '213', 'nama'  => 'danau lancang', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '214', 'nama'  => 'kusau makmaur', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '215', 'nama'  => 'talang danto', 'level' => '5', 'induk' => 201]);
        Wilayah::create(['id'  => '216', 'nama'  => 'KECAMATAN KAMPAR KIRI HULU', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '217', 'nama'  => 'aur kuning', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '218', 'nama'  => 'gajah bertalut', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '219', 'nama'  => 'tanjung beringin', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '220', 'nama'  => 'batu sanggan ', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '221', 'nama'  => 'tanjung belit', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '222', 'nama'  => 'gema', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '223', 'nama'  => 'tanjung belit selatan', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '224', 'nama'  => 'kota lama', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '225', 'nama'  => 'ludai', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '226', 'nama'  => 'pangkalan kapas', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '227', 'nama'  => 'kebun tinggi', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '228', 'nama'  => 'batu sasak', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '229', 'nama'  => 'tanjung karang', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '230', 'nama'  => 'pangkalan serai', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '231', 'nama'  => 'danau sontul', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '232', 'nama'  => 'dua sepakat', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '233', 'nama'  => 'terusan ', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '234', 'nama'  => 'deras tajak', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '235', 'nama'  => 'sungai santi', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '236', 'nama'  => 'sebayang jaya', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '237', 'nama'  => 'tanjung permai', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '238', 'nama'  => 'bukit betung', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '239', 'nama'  => 'lubuk bigau', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '240', 'nama'  => 'muara bio', 'level' => '5', 'induk' => 216]);
        Wilayah::create(['id'  => '241', 'nama'  => 'KECAMATAN GUNUNG SAHILAM', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '242', 'nama'  => 'kebun duruan', 'level' => '5', 'induk' => 241]);
        Wilayah::create(['id'  => '243', 'nama'  => 'sebalak', 'level' => '5', 'induk' => 241]);
        Wilayah::create(['id'  => '244', 'nama'  => 'gunung sahilan', 'level' => '5', 'induk' => 241]);
        Wilayah::create(['id'  => '245', 'nama'  => 'suka makmur ', 'level' => '5', 'induk' => 241]);
        Wilayah::create(['id'  => '246', 'nama'  => 'gunung sari', 'level' => '5', 'induk' => 241]);
        Wilayah::create(['id'  => '247', 'nama'  => 'makmur sejahtera', 'level' => '5', 'induk' => 241]);
        Wilayah::create(['id'  => '248', 'nama'  => 'sahilan darussalam ', 'level' => '5', 'induk' => 241]);
        Wilayah::create(['id'  => '249', 'nama'  => 'gunung mulya', 'level' => '5', 'induk' => 241]);
        Wilayah::create(['id'  => '250', 'nama'  => 'sungai lipai', 'level' => '5', 'induk' => 241]);
        Wilayah::create(['id'  => '251', 'nama'  => 'KECAMATAN XIII KOTO KAMPAR', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '252', 'nama'  => 'batu bersurat', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '253', 'nama'  => 'balung', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '254', 'nama'  => 'pulau gadung', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '255', 'nama'  => 'tanjung alai', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '256', 'nama'  => 'koto tuo', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '257', 'nama'  => 'muara takus', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '258', 'nama'  => 'gunung bungsu ', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '259', 'nama'  => 'koto mesjid', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '260', 'nama'  => 'lubuk agung', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '261', 'nama'  => 'ranah sungkai', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '262', 'nama'  => 'binamang', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '263', 'nama'  => 'pongkai istiqomah', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '264', 'nama'  => 'koto tuo barat', 'level' => '5', 'induk' => 251]);
        Wilayah::create(['id'  => '265', 'nama'  => 'KECAMATAN KOTO KAMPAR HULU', 'level' => '4', 'induk' => 1]);
        Wilayah::create(['id'  => '266', 'nama'  => 'tanjung ', 'level' => '5', 'induk' => 265]);
        Wilayah::create(['id'  => '267', 'nama'  => 'tabing', 'level' => '5', 'induk' => 265]);
        Wilayah::create(['id'  => '268', 'nama'  => 'pongkai', 'level' => '5', 'induk' => 265]);
        Wilayah::create(['id'  => '269', 'nama'  => 'gunung maselo', 'level' => '5', 'induk' => 265]);
        Wilayah::create(['id'  => '270', 'nama'  => 'bandur picak', 'level' => '5', 'induk' => 265]);
        Wilayah::create(['id'  => '271', 'nama'  => 'sibiruang', 'level' => '5', 'induk' => 265]);
    }
}
